version: '3.9'
services:
  user:
    container_name: user
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=user
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/eLearning

  course:
    container_name: course
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=course
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/eLearning

  lessons:
    container_name: lessons
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=lessons
    restart: always
    ports:
      - 3002:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/eLearning

  enrollment:
    container_name: enrollment
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP=enrollment
    restart: always
    ports:
      - 3003:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/eLearning  

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

# Define named volumes
volumes:
  mongo-data:
    driver: local