export const EL_DATABASE_CONNECTION = 'EL_DATABASE_CONNECTION';

export const USER_MODEL = 'USER_MODEL';
export const COURSE_MODEL = 'COURSE_MODEL';
export const LESSONS_MODEL = 'LESSONS_MODEL';
export const ENROLLEMENT_MODEL = 'ENROLLEMENT_MODEL';
